
import { TimelineEvent, Era } from './types';

export const TIMELINE_DATA: TimelineEvent[] = [
  // ERA 1
  {
    id: "e1-1",
    year: "1881",
    author: "Simon Newcomb",
    title: "Note on the Frequency of Use of the Different Digits in Natural Numbers",
    reference: "American Journal of Mathematics, 4(1), 39-40.",
    doi: "https://doi.org/10.2307/2369148",
    url: "https://www.jstor.org/stable/2369148",
    role: "El descubridor empírico. Observó el desgaste desigual en las páginas de los libros de tablas de logaritmos. Es el punto de partida histórico.",
    era: Era.ERA_1,
  },
  {
    id: "e1-2",
    year: "1938",
    author: "Frank Benford",
    title: "The Law of Anomalous Numbers",
    reference: "Proceedings of the American Philosophical Society, 78(4), 551-572.",
    url: "https://www.jstor.org/stable/984802",
    role: "El formalizador. Demostró la ley en miles de datos y definió la ecuación logarítmica exacta que se usará para evaluar la Base de datos #1 (Real legítima).",
    era: Era.ERA_1,
  },
  // ERA 2
  {
    id: "e2-1",
    year: "1996",
    author: "Mark J. Nigrini",
    title: "A taxpayer compliance application of Benford’s Law",
    reference: "The Journal of the American Taxation Association, 18(1), 72-91.",
    url: "https://www.proquest.com/docview/211023799",
    role: "La primera aplicación forense real. Demuestra empíricamente que los humanos no sabemos inventar números que sigan distribuciones naturales.",
    era: Era.ERA_2,
  },
  {
    id: "e2-2",
    year: "1997",
    author: "Mark J. Nigrini & Linda J. Mittermaier",
    title: "The Use of Benford's Law as an Aid in Analytical Procedures",
    reference: "Auditing: A Journal of Practice & Theory, 16(2), 52-67.",
    url: "https://www.proquest.com/docview/216734639",
    role: "El estándar de auditoría. Establece las pruebas estadísticas clásicas (como el análisis del primer dígito y primeros dos dígitos).",
    era: Era.ERA_2,
  },
  {
    id: "e2-3",
    year: "2007",
    author: "Andreas Diekmann",
    title: "Not the first digit! Using Benford's law to detect fraudulent scientific data",
    reference: "Journal of Applied Statistics, 34(3), 321-329.",
    doi: "https://doi.org/10.1080/02664760601004940",
    url: "https://www.tandfonline.com/doi/full/10.1080/02664760601004940",
    role: "El análisis del sesgo humano. Comprueba que los humanos a veces logran 'fingir' el primer dígito, pero se delatan en el segundo o tercero.",
    era: Era.ERA_2,
  },
  {
    id: "e2-4",
    year: "2009",
    author: "Mark J. Nigrini & Steven J. Miller",
    title: "Data diagnostics using second-order tests of Benford’s Law",
    reference: "Auditing: A Journal of Practice & Theory, 28(2), 305-324.",
    doi: "https://doi.org/10.2308/aud.2009.28.2.305",
    url: "https://www.proquest.com/docview/216745610",
    role: "Pruebas avanzadas. Introduce las pruebas de 'segundo orden', vitales para desenmascarar generadores aleatorios simples.",
    era: Era.ERA_2,
  },
  // ERA 3
  {
    id: "e3-1",
    year: "2014",
    author: "Alex Ely Kossovsky",
    title: "Benford’s law: Theory, the general law of relative quantities, and forensic fraud detection applications",
    reference: "World Scientific.",
    url: "https://research-ebsco-com.ezproxy.uninorte.edu.co/linkprocessor/plink?id=985c871a-c9b3-37f8-94f4-938d6ddc2906",
    role: "La guía métrica. La fuente para las fórmulas de bondad de ajuste: Chi-cuadrado y MAD.",
    era: Era.ERA_3,
  },
  {
    id: "e3-2",
    year: "2019",
    author: "Nirosh Kuruppu",
    title: "The Application of Benford's Law in Fraud Detection: A Systematic Methodology",
    reference: "International Business Research, 12(10), 1.",
    doi: "https://doi.org/10.5539/ibr.v12n10p1",
    url: "https://www.ccsenet.org/journal/index.php/ibr/article/view/0/40726",
    role: "Metodología sistemática pura. Establece un 'paso a paso' procedimental de cómo aplicar Benford de forma estructurada.",
    era: Era.ERA_3,
  },
  {
    id: "e3-3",
    year: "2019",
    author: "K. L. Kurien & A. A. Chikkamannur",
    title: "Benford's Law and Deep Learning Autoencoders: Fraud Detection in Social Media",
    reference: "4th IEEE International Conference RTEICT.",
    doi: "https://doi.org/10.1109/RTEICT46194.2019.9016804",
    url: "https://ieeexplore.ieee.org/document/9016804/",
    role: "El inicio del Deep Learning. Marca el uso de redes neuronales (Autoencoders) para aprender las representaciones latentes de los datos.",
    era: Era.ERA_3,
  },
  {
    id: "e3-4",
    year: "2020",
    author: "K. L. Kurien & A. A. Chikkamannur",
    title: "An Ameliorated hybrid model for Fraud Detection based on Tree based algorithms",
    reference: "3rd International Conference ICAECC.",
    doi: "https://doi.org/10.1109/ICAECC50550.2020.9339471",
    url: "https://ieeexplore.ieee.org/document/9339471",
    role: "Transición a modelos de ML clásicos. Justifica el uso de algoritmos basados en árboles (como Random Forest).",
    era: Era.ERA_3,
  },
  {
    id: "e3-5",
    year: "2021",
    author: "Félix Balado & Guénolé C.M. Silvestre",
    title: "BENFORD'S LAW: HAMMERING A SQUARE PEG INTO A ROUND HOLE?",
    reference: "European Signal Processing Conference.",
    doi: "https://doi.org/10.23919/EUSIPCO54536.2021.9616057",
    url: "https://ieeexplore.ieee.org/document/9616057",
    role: "La crítica (Limitaciones). Fundamental para identificar las limitaciones de la ley y evitar falsos positivos.",
    era: Era.ERA_3,
  },
  // ERA 4
  {
    id: "e4-1",
    year: "2022",
    author: "Tianyi Chen & Charalampos E. Tsourakakis",
    title: "AntiBenford Subgraphs: Unsupervised Anomaly Detection in Financial Networks",
    reference: "Proceedings of the ACM SIGKDD.",
    doi: "https://doi.org/10.1145/3534678.3539100",
    url: "https://dl.acm.org/doi/10.1145/3534678.3539100",
    role: "Patrones anómalos sintéticos. Introduce el ML no supervisado para detectar estructuras creadas específicamente para evadir la ley.",
    era: Era.ERA_4,
  },
  {
    id: "e4-2",
    year: "2023",
    author: "P. N. Kim et al.",
    title: "Economic Applications: from Traditional Use in Audits to Help in Deep Learning",
    reference: "International Journal of Uncertainty, Fuzziness and Knowledge-Based Systems.",
    doi: "https://doi.org/10.1142/S0218488523400111",
    url: "https://www.worldscientific.com/doi/10.1142/S0218488523400111",
    role: "El cambio de paradigma. Confirman que las desviaciones de Benford ahora deben usarse como features para modelos de Machine Learning.",
    era: Era.ERA_4,
  },
  {
    id: "e4-3",
    year: "Feb. 2024",
    author: "Pavel Y. Leonov et al.",
    title: "Improving the Methodology for Integrated Testing of Journal Entries by Benford's Law",
    reference: "Springer Chapter, ISBN/DOI link below.",
    doi: "https://doi.org/10.1007/978-3-031-50381-8_54",
    url: "https://link.springer.com/chapter/10.1007/978-3-031-50381-8_54",
    role: "El mapa metodológico. Combinan Benford con Random Forest y K-Means para mejorar el poder discriminativo.",
    era: Era.ERA_4,
  },
  {
    id: "e4-4",
    year: "2024",
    author: "Marco Di Marzio et al.",
    title: "Validating Benfordness on contaminated data",
    reference: "Socio-Economic Planning Sciences, 95.",
    doi: "https://doi.org/10.1016/j.seps.2024.102008",
    url: "https://www.sciencedirect.com/science/article/pii/S0038012124002076",
    role: "Fundamento de la Base de Datos Híbrida (#5). Explica qué ocurre cuando mezclas datos reales con fabricados.",
    era: Era.ERA_4,
  },
  {
    id: "e4-5",
    year: "2025",
    author: "Rathnakar Achary et al.",
    title: "Insurance Claim Fraud Detection using Benford's Method and Machine Learning",
    reference: "6th International Conference ICICV.",
    doi: "https://doi.org/10.1109/ICICV64824.2025.11085965",
    url: "https://ieeexplore.ieee.org/document/11085965",
    role: "Vigencia absoluta. Demuestra que el proyecto aborda un problema que se está publicando en la frontera estos mismos años.",
    era: Era.ERA_4,
  },
];
